from mlflow.exceptions import MlflowException as MlflowException
from mlflow.protos.databricks_pb2 import INVALID_PARAMETER_VALUE as INVALID_PARAMETER_VALUE
from mlflow.store.db.db_types import DATABASE_ENGINES as DATABASE_ENGINES
from mlflow.utils.os import is_windows as is_windows

def is_local_uri(uri): ...
def is_file_uri(uri): ...
def is_http_uri(uri): ...
def is_databricks_uri(uri): ...
def construct_db_uri_from_profile(profile): ...
def validate_db_scope_prefix_info(scope, prefix) -> None: ...
def get_db_info_from_uri(uri): ...
def get_databricks_profile_uri_from_artifact_uri(uri): ...
def remove_databricks_profile_info_from_artifact_uri(artifact_uri): ...
def add_databricks_profile_info_to_artifact_uri(artifact_uri, databricks_profile_uri): ...
def extract_db_type_from_uri(db_uri): ...
def get_uri_scheme(uri_or_path): ...
def extract_and_normalize_path(uri): ...
def append_to_uri_path(uri, *paths): ...
def is_databricks_acled_artifacts_uri(artifact_uri): ...
def is_databricks_model_registry_artifacts_uri(artifact_uri): ...
def is_valid_dbfs_uri(uri): ...
def dbfs_hdfs_uri_to_fuse_path(dbfs_uri): ...
